export const TRANSLATIONS = {
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    addSale: 'বিক্রয় যোগ করুন',
    addExpense: 'খরচ যোগ করুন',
    addCash: 'ক্যাশ যোগ করুন',
    history: 'লেনদেন ইতিহাস',
    report: 'মাসিক রিপোর্ট',
    notes: 'নোটস',
    settings: 'সেটিংস',
    balance: 'বর্তমান ব্যালেন্স',
    todaySales: 'আজকের বিক্রয়',
    todayExpenses: 'আজকের খরচ',
    monthlyProfit: 'মাসিক লাভ',
    recentTransactions: 'সাম্প্রতিক লেনদেন',
    productName: 'পণ্যের নাম',
    quantity: 'পরিমাণ',
    price: 'মূল্য',
    total: 'মোট',
    date: 'তারিখ',
    save: 'সংরক্ষণ করুন',
    expenseType: 'খরচের ধরন',
    title: 'শিরোনাম',
    amount: 'পরিমাণ',
    note: 'নোট',
    filter: 'ফিল্টার',
    edit: 'সম্পাদনা',
    delete: 'মুছে ফেলুন',
    adminLogin: 'অ্যাডমিন লগইন',
    password: 'পাসওয়ার্ড',
    login: 'লগইন',
    logout: 'লগআউট',
    language: 'ভাষা',
    darkMode: 'ডার্ক মোড',
    export: 'এক্সপোর্ট',
    profit: 'লাভ',
    loss: 'লোকসান',
    rent: 'ভাড়া',
    food: 'খাবার',
    transport: 'পরিবহন',
    other: 'অন্যান্য',
    investment: 'বিনিয়োগ',
    sale: 'বিক্রয়',
    expense: 'খরচ',
    cash: 'ক্যাশ',
    withdraw: 'টাকা উত্তোলন',
    cashHistory: 'লেনদেন ইতিহাস',
    withdrawHistory: 'উত্তোলন ইতিহাস',
    adminAccess: 'অ্যাডমিন অ্যাক্সেস',
    enterAdminPassword: 'ফিচারগুলো আনলক করতে অ্যাডমিন পাসওয়ার্ড দিন',
    unlockAdmin: 'অ্যাডমিন আনলক করুন',
    appearance: 'চেহারা',
    chooseLanguage: 'আপনার পছন্দের ভাষা নির্বাচন করুন',
    themeDescription: 'লাইট এবং ডার্ক থিমের মধ্যে পরিবর্তন করুন',
    dataManagement: 'ডাটা ম্যানেজমেন্ট',
    dangerZone: 'ডেঞ্জার জোন',
    clearTransactions: 'লেনদেন মুছুন',
    clearTransactionsDesc: 'সব বিক্রয় এবং খরচের ইতিহাস মুছে ফেলুন।',
    clearStock: 'স্টক মুছুন',
    clearStockDesc: 'সব পণ্য এবং স্টকের তথ্য মুছে ফেলুন।',
    clearCash: 'ক্যাশ/নোট মুছুন',
    clearCashDesc: 'সব ক্যাশ এন্ট্রি এবং নোট মুছে ফেলুন।',
    clearAllData: 'সব ডাটা মুছুন',
    clearAllDataDesc: 'এটি স্থায়ীভাবে সবকিছু মুছে ফেলবে। এটি আর ফিরে পাওয়া যাবে না।',
    clearEverything: 'সবকিছু মুছুন',
    enterClearPassword: 'মুছে ফেলার পাসওয়ার্ড দিন',
    confirmClearAll: 'আপনি কি নিশ্চিত? এটি সবকিছু মুছে ফেলবে এবং অ্যাপটিকে নতুন অবস্থায় ফিরিয়ে আনবে।',
    confirmClearTransactions: 'এটি সব বিক্রয় এবং খরচের ইতিহাস মুছে ফেলবে। এটি স্থায়ী।',
    confirmClearStock: 'এটি সব পণ্য এবং তাদের ইতিহাস মুছে ফেলবে। এটি স্থায়ী।',
    confirmClearCash: 'এটি সব ক্যাশ এন্ট্রি এবং নোট মুছে ফেলবে। এটি স্থায়ী।',
    yesClearData: 'হ্যাঁ, ডাটা মুছুন',
    noKeepData: 'না, ডাটা রাখুন',
    developedBy: 'ডেভেলপ করেছেন',
    visitorMode: 'ভিজিটর মোড',
    visitorModeDesc: 'আপনি বর্তমানে শুধুমাত্র দেখার মোডে আছেন।',
    visitorModeHint: 'এডিট করার জন্য সাইডবার বা লগইন পেজ থেকে অ্যাডমিন পাসওয়ার্ড দিন।',
    adminModeActive: 'অ্যাডমিন মোড সক্রিয়',
    adminModeDesc: 'আপনার কাছে সিস্টেম পরিচালনা করার পূর্ণ অ্যাক্সেস আছে।',
    restoreSaleStockError: 'বিক্রয় পুনরুদ্ধার করা যাচ্ছে না: সংশ্লিষ্ট পণ্যটি মুছে ফেলা হয়েছে। আগে পণ্যটি পুনরুদ্ধার করুন।',
    restoreSaleQtyError: 'বিক্রয় পুনরুদ্ধার করা যাচ্ছে না: অপর্যাপ্ত স্টক!',
    insufficientStock: 'অপর্যাপ্ত স্টক! উপলব্ধ: ',
    fillAllFields: 'অনুগ্রহ করে সব ঘর সঠিকভাবে পূরণ করুন',
    adminRequired: 'অ্যাডমিন অ্যাক্সেস প্রয়োজন',
    adminRequiredSale: 'বিক্রয় যোগ করতে অ্যাডমিন অ্যাক্সেস প্রয়োজন',
    adminRequiredExpense: 'খরচ যোগ করতে অ্যাডমিন অ্যাক্সেস প্রয়োজন',
    recordSaleDesc: 'নতুন পণ্যের বিক্রয় রেকর্ড করুন',
    recordExpenseDesc: 'ব্যবসায়িক খরচ রেকর্ড করুন',
    ownerInvestmentDesc: 'মালিকের বিনিয়োগ বা মূলধন যোগ',
    ownerWithdrawalDesc: 'মালিকের উত্তোলন বা ক্যাশ আউট',
    previousInvestments: 'পূর্ববর্তী বিনিয়োগ',
    previousCashOuts: 'পূর্ববর্তী উত্তোলন',
    lowStockWarning: 'কম স্টক সতর্কতা',
    selectProductFirst: 'আগে পণ্য নির্বাচন করুন',
    noSize: 'কোন সাইজ নেই',
    exportAll: 'সব ডাটা এক্সপোর্ট',
    exportBackup: 'সব ডাটার ব্যাকআপ ডাউনলোড করুন (বিক্রয়, খরচ, স্টক, নোট)',
    all: 'সব',
    noData: 'কোন তথ্য নেই',
    loading: 'লোড হচ্ছে...',
    success: 'সফলভাবে সম্পন্ন হয়েছে',
    error: 'কিছু ভুল হয়েছে',
    confirmDelete: 'আপনি কি নিশ্চিত যে আপনি এটি মুছে ফেলতে চান?',
    undo: 'পূর্বাবস্থায় ফিরুন',
    redo: 'পুনরায় করুন',
    activityLog: 'অ্যাক্টিভিটি লগ',
    salesHistory: 'বিক্রয় খতিয়ান',
    expenseHistory: 'খরচ খতিয়ান',
    dailyTotal: 'দৈনিক মোট',
    stockManagement: 'স্টক ম্যানেজমেন্ট',
    addStock: 'স্টক যোগ করুন',
    size: 'সাইজ',
    initialQuantity: 'শুরু পরিমাণ',
    currentQuantity: 'বর্তমান পরিমাণ',
    restock: 'রিস্টক',
    outOfStock: 'স্টক নেই',
    lowStock: 'কম স্টক',
    fromStock: 'স্টক থেকে',
    manualEntry: 'ম্যানুয়াল এন্ট্রি',
    selectProduct: 'পণ্য নির্বাচন করুন',
    selectSize: 'সাইজ নির্বাচন করুন',
    stockHistory: 'স্টক ইতিহাস',
    added: 'যোগ করা হয়েছে',
    sold: 'বিক্রি হয়েছে',
    viewDetails: 'বিস্তারিত দেখুন',
    daily: 'দৈনিক',
    monthly: 'মাসিক',
    custom: 'কাস্টম',
    recycleBin: 'রিসাইকেল বিন',
    restore: 'পুনরুদ্ধার',
    deletePermanently: 'স্থায়ীভাবে মুছে ফেলুন',
    deletedDate: 'মুছে ফেলার তারিখ',
    confirmPermanentDelete: 'আপনি কি নিশ্চিত যে আপনি এটি স্থায়ীভাবে মুছে ফেলতে চান? এটি আর ফিরে পাওয়া যাবে না।',
    enterPassword: 'পাসওয়ার্ড দিন',
    incorrectPassword: 'ভুল পাসওয়ার্ড',
    cancel: 'বাতিল',
    vsLastMonth: 'গত মাসের তুলনায়',
    lockAdmin: 'অ্যাডমিন লক করুন',
    configRequired: 'কনফিগারেশন প্রয়োজন',
    configDesc: 'দয়া করে AI Studio-র Settings > Secrets প্যানেলে আপনার Supabase ক্রেডেনশিয়াল যোগ করুন।',
    missing: 'অনুপস্থিত',
    totalInflow: 'মোট আয়',
    totalOutflow: 'মোট ব্যয়',
    netBalance: 'নিট ব্যালেন্স',
    searchTransactions: 'লেনদেন খুঁজুন...',
    type: 'ধরণ',
    description: 'বিবরণ',
    actions: 'অ্যাকশন',
    qty: 'পরিমাণ',
    month: 'মাস',
    sales: 'বিক্রয়',
    expenses: 'খরচ',
    dailyTrend: 'দৈনিক ট্রেন্ড (বর্তমান মাস)',
    expenseBreakdown: 'খরচের বিশ্লেষণ',
    recentMonthlySummary: 'সাম্প্রতিক মাসিক সারাংশ',
    confirmRestore: 'আপনি কি নিশ্চিত যে আপনি এটি পুনরুদ্ধার করতে চান?',
    cashEntry: 'ক্যাশ এন্ট্রি',
    totalSales: 'মোট বিক্রয়',
    totalExpenses: 'মোট খরচ',
    totalProfit: 'মোট লাভ',
  },
  en: {
    dashboard: 'Dashboard',
    addSale: 'Add Sale',
    addExpense: 'Add Expense',
    addCash: 'Add Cash',
    history: 'History',
    report: 'Monthly Report',
    notes: 'Notes',
    settings: 'Settings',
    balance: 'Current Balance',
    todaySales: 'Today\'s Sales',
    todayExpenses: 'Today\'s Expenses',
    monthlyProfit: 'Monthly Profit',
    recentTransactions: 'Recent Transactions',
    productName: 'Product Name',
    quantity: 'Quantity',
    price: 'Price',
    total: 'Total',
    date: 'Date',
    save: 'Save',
    expenseType: 'Expense Type',
    title: 'Title',
    amount: 'Amount',
    note: 'Note',
    filter: 'Filter',
    edit: 'Edit',
    delete: 'Delete',
    adminLogin: 'Admin Login',
    password: 'Password',
    login: 'Login',
    logout: 'Logout',
    language: 'Language',
    darkMode: 'Dark Mode',
    export: 'Export',
    profit: 'Profit',
    loss: 'Loss',
    rent: 'Rent',
    food: 'Food',
    transport: 'Transport',
    other: 'Other',
    investment: 'Investment',
    sale: 'Sale',
    expense: 'Expense',
    cash: 'Cash',
    withdraw: 'Withdraw Cash',
    cashHistory: 'Cash History',
    withdrawHistory: 'Withdrawal History',
    adminAccess: 'Admin Access',
    enterAdminPassword: 'Enter the admin password to unlock features',
    unlockAdmin: 'Unlock Admin',
    appearance: 'Appearance',
    chooseLanguage: 'Choose your preferred language',
    themeDescription: 'Switch between light and dark themes',
    dataManagement: 'Data Management',
    dangerZone: 'Danger Zone',
    clearTransactions: 'Clear Transactions',
    clearTransactionsDesc: 'Delete all sales and expenses history.',
    clearStock: 'Clear Stock',
    clearStockDesc: 'Delete all products and stock logs.',
    clearCash: 'Clear Cash/Notes',
    clearCashDesc: 'Delete all cash entries and notes.',
    clearAllData: 'Clear All Data',
    clearAllDataDesc: 'This will permanently delete EVERYTHING. This action cannot be undone.',
    clearEverything: 'Clear Everything',
    enterClearPassword: 'Enter Clear Password',
    confirmClearAll: 'Are you absolutely sure? This will delete everything and reset the app to a clean state.',
    confirmClearTransactions: 'This will delete all sales and expenses history. This action is permanent.',
    confirmClearStock: 'This will delete all products and their history. This action is permanent.',
    confirmClearCash: 'This will delete all cash entries and notes. This action is permanent.',
    yesClearData: 'Yes, Clear Data',
    noKeepData: 'No, Keep Data',
    developedBy: 'Developed By',
    visitorMode: 'Visitor Mode',
    visitorModeDesc: 'You are currently in read-only mode.',
    visitorModeHint: 'To enable editing, please enter the admin password from the sidebar or the login page.',
    adminModeActive: 'Admin Mode Active',
    adminModeDesc: 'You have full access to manage the system.',
    restoreSaleStockError: 'Cannot restore sale: Associated product is deleted. Restore the product first.',
    restoreSaleQtyError: 'Cannot restore sale: Insufficient stock!',
    insufficientStock: 'Insufficient stock! Available: ',
    fillAllFields: 'Please fill all fields correctly',
    adminRequired: 'Admin access required',
    adminRequiredSale: 'Admin access required to add sales',
    adminRequiredExpense: 'Admin access required to add expenses',
    recordSaleDesc: 'Record a new product sale',
    recordExpenseDesc: 'Record a business expense',
    ownerInvestmentDesc: 'Owner investment or capital add',
    ownerWithdrawalDesc: 'Owner withdrawal or cash out',
    previousInvestments: 'Previous investments',
    previousCashOuts: 'Previous cash outs',
    lowStockWarning: 'low stock warning',
    selectProductFirst: 'Select product first',
    noSize: 'No Size',
    exportAll: 'Export All Data',
    exportBackup: 'Download full backup (Sales, Expenses, Stock, Notes)',
    all: 'All',
    noData: 'No Data Found',
    loading: 'Loading...',
    success: 'Operation Successful',
    error: 'Something went wrong',
    confirmDelete: 'Are you sure you want to delete this?',
    undo: 'Undo',
    redo: 'Redo',
    activityLog: 'Activity Log',
    salesHistory: 'Sales History',
    expenseHistory: 'Expense History',
    dailyTotal: 'Daily Total',
    stockManagement: 'Stock Management',
    addStock: 'Add Stock',
    size: 'Size',
    initialQuantity: 'Initial Qty',
    currentQuantity: 'Current Qty',
    restock: 'Restock',
    outOfStock: 'Out of Stock',
    lowStock: 'Low Stock',
    fromStock: 'From Stock',
    manualEntry: 'Manual Entry',
    selectProduct: 'Select Product',
    selectSize: 'Select Size',
    stockHistory: 'Stock History',
    added: 'Added',
    sold: 'Sold',
    viewDetails: 'View Details',
    daily: 'Daily',
    monthly: 'Monthly',
    custom: 'Custom',
    recycleBin: 'Recycle Bin',
    restore: 'Restore',
    deletePermanently: 'Delete Permanently',
    deletedDate: 'Deleted Date',
    confirmPermanentDelete: 'Are you sure you want to delete this permanently? This action cannot be undone.',
    enterPassword: 'Enter Password',
    incorrectPassword: 'Incorrect Password',
    cancel: 'Cancel',
    vsLastMonth: 'vs last month',
    lockAdmin: 'Lock Admin',
    configRequired: 'Configuration Required',
    configDesc: 'Please add your Supabase credentials to the Settings > Secrets panel in AI Studio.',
    missing: 'Missing',
    totalInflow: 'Total Inflow',
    totalOutflow: 'Total Outflow',
    netBalance: 'Net Balance',
    searchTransactions: 'Search transactions...',
    type: 'Type',
    description: 'Description',
    actions: 'Actions',
    qty: 'Qty',
    month: 'Month',
    sales: 'Sales',
    expenses: 'Expenses',
    dailyTrend: 'Daily Trend (Current Month)',
    expenseBreakdown: 'Expense Breakdown',
    recentMonthlySummary: 'Recent Monthly Summary',
    confirmRestore: 'Are you sure you want to restore this?',
    cashEntry: 'Cash Entry',
    totalSales: 'Total Sales',
    totalExpenses: 'Total Expenses',
    totalProfit: 'Total Profit',
  }
};

export type Language = 'bn' | 'en';
