export const TRANSLATIONS = {
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    addSale: 'বিক্রয় যোগ করুন',
    addExpense: 'খরচ যোগ করুন',
    addCash: 'ক্যাশ যোগ করুন',
    history: 'লেনদেন ইতিহাস',
    report: 'মাসিক রিপোর্ট',
    notes: 'নোটস',
    settings: 'সেটিংস',
    balance: 'বর্তমান ব্যালেন্স',
    todaySales: 'আজকের বিক্রয়',
    todayExpenses: 'আজকের খরচ',
    monthlyProfit: 'মাসিক লাভ',
    recentTransactions: 'সাম্প্রতিক লেনদেন',
    productName: 'পণ্যের নাম',
    quantity: 'পরিমাণ',
    price: 'মূল্য',
    total: 'মোট',
    date: 'তারিখ',
    save: 'সংরক্ষণ করুন',
    expenseType: 'খরচের ধরন',
    title: 'শিরোনাম',
    amount: 'পরিমাণ',
    note: 'নোট',
    filter: 'ফিল্টার',
    edit: 'সম্পাদনা',
    delete: 'মুছে ফেলুন',
    adminLogin: 'অ্যাডমিন লগইন',
    password: 'পাসওয়ার্ড',
    login: 'লগইন',
    logout: 'লগআউট',
    language: 'ভাষা',
    darkMode: 'ডার্ক মোড',
    export: 'এক্সপোর্ট',
    profit: 'লাভ',
    loss: 'লোকসান',
    rent: 'ভাড়া',
    food: 'খাবার',
    transport: 'পরিবহন',
    other: 'অন্যান্য',
    investment: 'বিনিয়োগ',
    sale: 'বিক্রয়',
    expense: 'খরচ',
    cash: 'ক্যাশ',
    all: 'সব',
    noData: 'কোন তথ্য নেই',
    loading: 'লোড হচ্ছে...',
    success: 'সফলভাবে সম্পন্ন হয়েছে',
    error: 'কিছু ভুল হয়েছে',
    confirmDelete: 'আপনি কি নিশ্চিত যে আপনি এটি মুছে ফেলতে চান?',
    undo: 'পূর্বাবস্থায় ফিরুন',
    redo: 'পুনরায় করুন',
    activityLog: 'অ্যাক্টিভিটি লগ',
    salesHistory: 'বিক্রয় খতিয়ান',
    expenseHistory: 'খরচ খতিয়ান',
    dailyTotal: 'দৈনিক মোট',
    stockManagement: 'স্টক ম্যানেজমেন্ট',
    addStock: 'স্টক যোগ করুন',
    size: 'সাইজ',
    initialQuantity: 'শুরু পরিমাণ',
    currentQuantity: 'বর্তমান পরিমাণ',
    restock: 'রিস্টক',
    outOfStock: 'স্টক নেই',
    lowStock: 'কম স্টক',
    fromStock: 'স্টক থেকে',
    manualEntry: 'ম্যানুয়াল এন্ট্রি',
    selectProduct: 'পণ্য নির্বাচন করুন',
    selectSize: 'সাইজ নির্বাচন করুন',
    stockHistory: 'স্টক ইতিহাস',
    added: 'যোগ করা হয়েছে',
    sold: 'বিক্রি হয়েছে',
    viewDetails: 'বিস্তারিত দেখুন',
    monthly: 'মাসিক',
    custom: 'কাস্টম',
    recycleBin: 'রিসাইকেল বিন',
    restore: 'পুনরুদ্ধার',
    deletePermanently: 'স্থায়ীভাবে মুছে ফেলুন',
    deletedDate: 'মুছে ফেলার তারিখ',
    confirmPermanentDelete: 'আপনি কি নিশ্চিত যে আপনি এটি স্থায়ীভাবে মুছে ফেলতে চান? এটি আর ফিরে পাওয়া যাবে না।',
    enterPassword: 'পাসওয়ার্ড দিন',
    incorrectPassword: 'ভুল পাসওয়ার্ড',
  },
  en: {
    dashboard: 'Dashboard',
    addSale: 'Add Sale',
    addExpense: 'Add Expense',
    addCash: 'Add Cash',
    history: 'History',
    report: 'Monthly Report',
    notes: 'Notes',
    settings: 'Settings',
    balance: 'Current Balance',
    todaySales: 'Today\'s Sales',
    todayExpenses: 'Today\'s Expenses',
    monthlyProfit: 'Monthly Profit',
    recentTransactions: 'Recent Transactions',
    productName: 'Product Name',
    quantity: 'Quantity',
    price: 'Price',
    total: 'Total',
    date: 'Date',
    save: 'Save',
    expenseType: 'Expense Type',
    title: 'Title',
    amount: 'Amount',
    note: 'Note',
    filter: 'Filter',
    edit: 'Edit',
    delete: 'Delete',
    adminLogin: 'Admin Login',
    password: 'Password',
    login: 'Login',
    logout: 'Logout',
    language: 'Language',
    darkMode: 'Dark Mode',
    export: 'Export',
    profit: 'Profit',
    loss: 'Loss',
    rent: 'Rent',
    food: 'Food',
    transport: 'Transport',
    other: 'Other',
    investment: 'Investment',
    sale: 'Sale',
    expense: 'Expense',
    cash: 'Cash',
    all: 'All',
    noData: 'No Data Found',
    loading: 'Loading...',
    success: 'Operation Successful',
    error: 'Something went wrong',
    confirmDelete: 'Are you sure you want to delete this?',
    undo: 'Undo',
    redo: 'Redo',
    activityLog: 'Activity Log',
    salesHistory: 'Sales History',
    expenseHistory: 'Expense History',
    dailyTotal: 'Daily Total',
    stockManagement: 'Stock Management',
    addStock: 'Add Stock',
    size: 'Size',
    initialQuantity: 'Initial Qty',
    currentQuantity: 'Current Qty',
    restock: 'Restock',
    outOfStock: 'Out of Stock',
    lowStock: 'Low Stock',
    fromStock: 'From Stock',
    manualEntry: 'Manual Entry',
    selectProduct: 'Select Product',
    selectSize: 'Select Size',
    stockHistory: 'Stock History',
    added: 'Added',
    sold: 'Sold',
    viewDetails: 'View Details',
    monthly: 'Monthly',
    custom: 'Custom',
    recycleBin: 'Recycle Bin',
    restore: 'Restore',
    deletePermanently: 'Delete Permanently',
    deletedDate: 'Deleted Date',
    confirmPermanentDelete: 'Are you sure you want to delete this permanently? This action cannot be undone.',
    enterPassword: 'Enter Password',
    incorrectPassword: 'Incorrect Password',
  }
};

export type Language = 'bn' | 'en';
